owner: scratchsuite
repo: scratchsuite.github.io

# Add your sites here
sites:
  - name: Scratch
    url: https://scratch.mit.edu
  - name: Scratch - Lab
    url: https://lab.scratch.mit.edu
  - name: Scratch - Day
    url: https://day.scratch.mit.edu
  - name: Scratch - Forums
    url: https://scratch.mit.edu/discuss
  - name: Scratch - Uploads (Scratch 2)
    url: https://uploads.scratch.mit.edu/
    expectedStatusCodes:
      - 403
      - 404
  - name: Scratch in Practice
    url: https://sip.scratch.mit.edu/
  - name: Scratch - Wiki
    url: https://scratch-wiki.info
  - name: Scratch - ScratchJr
    url: https://www.scratchjr.org/
  - name: Scratch Foundation
    url: https://www.scratchfoundation.org/

status-website:
  baseUrl: /frontend
  logoUrl: https://scratchsuite.github.io/assets/upptime-icon.svg
  name: Scratch Suite
  cname: scratchsuite.github.io
  introTitle: "Scratch Status"
  introMessage: Use this site to see if scratch is down. 
  navbar:
    - title: Frontend
      href: /frontend
    - title: Backend
      href: /backend
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  customBodyHtml: "<iframe src='/assets/topbar.html' height='65px' width='100%' style='border-width:0; overflow:hidden;'></iframe>"
i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org) and created for use for everybody at [Scratch](https://scratch.mit.edu). Scratch is developed by the Lifelong Kindergarten Group at the MIT Media Lab. See [scratch.mit.edu](https://scratch.mit.edu). ScratchStatus is not affilated in any way with Scratch. If you want to help improve this, comment on [my profile](https://scratch.mit.edu/users/9gr)
